[FileDialog]
history=file:///home/courses/desdigsys2/2026s/dds226s15, file:///home/courses/desdigsys2/2026s/dds226s15/projects/jkff, file:///home/courses/desdigsys2/2026s/dds226s15/projects/logic_unit, file:///home/courses/desdigsys2/2026s/dds226s15/projects/processor, file:///home/courses/desdigsys2/2026s/dds226s15/projects/readserial
lastVisited=file:///home/courses/desdigsys2/2026s/dds226s15/projects/readserial
qtVersion=5.15.10
shortcuts=file:, file:///home/courses/desdigsys2/2026s/dds226s15
sidebarWidth=110
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x8b\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1R\0\0\0\x1\0\0\0\0\0\0\0S\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0\x90\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
